name: puellascript
version: 0.0.1
category: Language
synopsis: A proof-of-concept Haskell to WebAssembly compiler.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/puellascript

custom-setup:
  dependencies:
    - base
    - binary
    - Cabal
    - filepath

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - directory
  - filepath
  - ghc
  - ghci
  - hoopl
  - process

library:
  source-dirs: src

executables:
  phc:
    source-dirs: app
    main: phc.hs
    dependencies:
      - puellascript

